export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const USERS_LOADING = 'USERS_LOADING'
export const USERS_FAILED = 'USERS_FAILED'
export const ADD_USERS = 'ADD_USERS'

export const ORGS_LOADING = 'ORGS_LOADING'
export const ORGS_FAILED = 'ORGS_FAILED'
export const ADD_ORGS = 'ADD_ORGS'

export const VOLUNTEERS_LOADING = 'VOLUNTEERS_LOADING'
export const ADD_VOLUNTEERS = 'ADD_VOLUNTEERS'
export const VOLUNTEERS_FAILED = 'VOLUNTEERS_FAILED'

export const CAUSES_LOADING = 'CAUSES_LOADING'
export const CAUSES_FAILED = 'CAUSES_FAILED'
export const ADD_CAUSES = 'ADD_CAUSES'
export const ADD_CAUSE_ITEM = 'ADD_CAUSE_ITEM'

export const SKILLS_LOADING = 'SKILLS_LOADING'
export const SKILLS_FAILED = 'SKILLS_FAILED'
export const ADD_SKILLS = 'ADD_SKILLS'
export const ADD_SKILL_ITEM = 'ADD_SKILL_ITEM'

export const PROJECTS_LOADING = 'PROJECTS_LOADING'
export const PROJECTS_FAILED = 'PROJECTS_FAILED'
export const ADD_PROJECTS = 'ADD_PROJECTS'
export const ADD_PROJECT_ITEM = 'ADD_PROJECT_ITEM'

export const HELPS_LOADING = 'HELPS_LOADING'
export const HELPS_FAILED = 'HELPS_FAILED'
export const ADD_HELPS = 'ADD_HELPS'
export const ADD_HELP_ITEM = 'ADD_HELP_ITEM'

export const APPS_LOADING = 'APPS_LOADING'
export const APPS_FAILED = 'APPS_FAILED'
export const ADD_APPS = 'ADD_APPS'
export const ADD_APP_ITEM = 'ADD_APP_ITEM'

export const NET_REQUEST_LOADING = 'NET_REQUEST_LOADING'
export const NET_REQUEST_SUCCESS = 'NET_REQUEST_SUCCESS'
export const NET_REQUEST_FAILED = 'NET_REQUEST_FAILED'
